/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This object represents Collections in a SpatioTemporal Asset Catalog.
 */
export type STACCollectionSpecification = STACCatalogSpecification & STACCollection;
/**
 * This object represents Catalogs in a SpatioTemporal Asset Catalog.
 */
export type STACCatalogSpecification = Catalog;
export type STACVersion = string;
export type ReferenceToAJSONSchema = string;
export type ReferenceToACoreExtension = string;
export type STACExtensions = (ReferenceToAJSONSchema | ReferenceToACoreExtension)[];
export type Identifier = string;
export type Title = string;
export type Description = string;
export type LinkReference = string;
export type LinkRelationType = string;
export type LinkType = string;
export type LinkTitle = string;
export type Links = {
  href: LinkReference;
  rel: LinkRelationType;
  type?: LinkType;
  title?: LinkTitle;
  [k: string]: unknown;
}[];
export type ReferenceToAJSONSchema1 = string;
export type ReferenceToACoreExtension1 = string;
export type STACExtensions1 = (ReferenceToAJSONSchema1 | ReferenceToACoreExtension1)[];
export type Keywords = string[];
export type CollectionLicenseName = string;
export type OrganizationName = string;
export type OrganizationDescription = string;
export type OrganizationRoles = ('producer' | 'licensor' | 'processor' | 'host')[];
export type OrganizationHomepage = string;
export type SpatialExtents = [SpatialExtent, ...SpatialExtent[]];
export type SpatialExtent = unknown[];
export type TemporalExtents = [TemporalExtent, ...TemporalExtent[]];
export type TemporalExtent = [string | null, string | null];
export type MinimumValue2 = MinimumValue | MinimumValue1;
export type MinimumValue = number;
export type MinimumValue1 = string;
export type MaximumValue2 = MaximumValue | MaximumValue1;
export type MaximumValue = number;
export type MaximumValue1 = string;
export type SetOfValues = unknown[];

export interface Catalog {
  stac_version: STACVersion;
  stac_extensions?: STACExtensions;
  id: Identifier;
  title?: Title;
  description: Description;
  links: Links;
  [k: string]: unknown;
}
/**
 * These are the fields specific to a STAC Collection. All other fields are inherited from STAC Catalog.
 */
export interface STACCollection {
  stac_extensions?: STACExtensions1;
  keywords?: Keywords;
  license: CollectionLicenseName;
  providers?: {
    name?: OrganizationName;
    description?: OrganizationDescription;
    roles?: OrganizationRoles;
    url?: OrganizationHomepage;
    [k: string]: unknown;
  }[];
  extent: Extents;
  summaries?: {
    [k: string]: Stats | SetOfValues;
  };
  [k: string]: unknown;
}
export interface Extents {
  spatial: SpatialExtentObject;
  temporal: TemporalExtentObject;
  [k: string]: unknown;
}
export interface SpatialExtentObject {
  bbox: SpatialExtents;
  [k: string]: unknown;
}
export interface TemporalExtentObject {
  interval: TemporalExtents;
  [k: string]: unknown;
}
export interface Stats {
  min: MinimumValue2;
  max: MaximumValue2;
  [k: string]: unknown;
}
