/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { StacExtensions, StacLink, StacVersion } from './common';

/**
 * This object represents Catalogs in a SpatioTemporal Asset Catalog.
 */

export interface StacCatalog {
  stac_version: StacVersion;
  stac_extensions?: StacExtensions;
  type: 'Catalog';
  id: string;
  title?: string;
  description: string;
  links: StacLink[];
  [k: string]: unknown;
}
