/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { StacAsset, StacExtensions, StacLink, StacRoles, StacVersion } from './common';

/**
 * This object represents Collections in a SpatioTemporal Asset Catalog.
 */

type Keywords = string[];

// type OrganizationRoles = ('producer' | 'licensor' | 'processor' | 'host')[];
type SpatialExtents = [SpatialExtent, ...SpatialExtent[]];
type SpatialExtent = number[];

type TemporalExtents = [TemporalExtent, ...TemporalExtent[]];
type TemporalExtent = [string | null, string | null];

/**
 * These are the fields specific to a STAC Collection. All other fields are inherited from STAC Catalog.
 */
interface StacCollection {
  stac_version: StacVersion;
  stac_extensions?: StacExtensions;
  type: 'Collection';
  id: string;
  title?: string;
  description: string;
  keywords?: Keywords;
  license: string;
  providers?: {
    name: string;
    description?: string;
    roles?: StacRoles[];
    url?: string;
    [k: string]: unknown;
  }[];
  extent: Extents;
  assets?: { [k: string]: StacAsset };
  links: StacLink[];
  summaries?: Summaries;
  [k: string]: unknown;
}

interface Extents {
  spatial: SpatialExtentObject;
  temporal: TemporalExtentObject;
  [k: string]: unknown;
}
interface SpatialExtentObject {
  bbox: SpatialExtents;
  [k: string]: unknown;
}
interface TemporalExtentObject {
  interval: TemporalExtents;
  [k: string]: unknown;
}

interface Summaries {
  [k: string]: Range | unknown;
}
interface Range {
  minimum: number | string;
  maximum: number | string;
  [k: string]: unknown;
}
