/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { CommonMetadata, StacAsset, StacExtensions, StacLink, StacVersion } from './common.js';
import type { GeoJSONFeature } from './geojson.js';

/**
 * This object represents the metadata for an item in a SpatioTemporal Asset Catalog.
 */
export type StacItem = GeoJSONFeature & {
  stac_version: StacVersion;
  stac_extensions?: StacExtensions;
  id: string;
  /**
   * The ID of the STAC Collection this Item references to.
   *
   * Only exists if {@link StacItem.links} contain a `{"rel": "collection"}`
   */
  collection?: string;
  links: StacLink[];
  assets: { [k: string]: StacAsset };
  properties: CommonMetadata &
    (
      | {
          datetime: {
            [k: string]: unknown;
          };
          [k: string]: unknown;
        }
      | {
          [k: string]: unknown;
        }
    );
  [k: string]: unknown;
};
